### PR TITLE
Yorick mirage

### PR DESCRIPTION
**Pull request by mor1**
Don't merge yet, still testing. Does for `.travis-mirage.sh` what @dsheets did for `.travis-opam.sh`.

@dsheets Some thoughts on `Yorick`:

+ Didn't realise that `$CWD` isn't maintained between `?|` commands
+ Should understand / be more consistent about output during execution (`set +ex` etc)
+ Need to use nested `"` to make sure shell and OCaml treat contents correctly (strings in which variable substitution is carried out) is a bit awkward

Other than that, mostly OK I think.

### CODE REVIEW

**Comment by mor1** [comment]
Ok, this seems to work. @dsheets @samoht thoughts?

**Comment by dsheets** [comment]
I think we're both offline until late Monday now. I'll review any still pending and incorporate updates then.

**Comment by dsheets** [comment]
This looks reasonable to me. I haven't tested it and don't know which systems use it so I trust that you've ensured it is sufficient for your needs.

Regarding your comments about Yorick:

1. I've opened #46 to address the `$CWD` issue
2. I'm not sure I understand "Should understand / be more consistent about output during execution (set +ex etc)". I've thought about having Yorick open up a single subshell and use it for all commands in order to maintain shell state. Annoyingly, this still risks state desynchronization so I'd like to see how much mileage we can get from just lifting the most used bits of state into OCaml (e.g. `set`, `export`, `cd`).
3. You may want `q` or `ql` with `*~`. There is a trade-off and perhaps an `exec` form taking a sequence of arguments should also be exposed.

**Comment by mor1** [comment]
It built and deployed my site at least once...

Re points:

1. cool
2. might be addressed through readme/other docs. but the apparently arbitrary use of `set +ex` / `set +uex` / etc that i thought i saw was confusing. (ideally perhaps this might be Yet Another Parameter...?)
3. perhaps all i want is docs ;) specifically though, l.103 is the line where this mildly irritated me, and it probably could be solved by escaping (and if possible, better support than the default for multi-line strings).

**Comment by samoht** [comment]
Merging because I need the `EXTRA_REMOTES` to test mirage-www. Improvement are welcome in subsequent PRs.

**Pull request merged**
