### PR TITLE
Added option for rebuilding reverse dependencies

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This PR is intended as a starting point for discussion on solving #1. I just did the easiest thing imaginable, not sure if I forgot something. If so, let me know.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Any opinions on this? @samoht?

**Comment by samoht** [comment]
ha sorry I missed your PR! sounds good to me, can you rebase it please?

**Comment by Leonidas-from-XIV** [comment]
Sure, I just rebased it!

**Comment by samoht** [comment]
thanks!

**Pull request merged**
