### PR TITLE
fix script

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
@samoht sorry, seems my last PR/commit broke the script (see https://travis-ci.org/mirleft/ocaml-nocrypto/jobs/61740407#L379)

**Comment by samoht** [comment]
You need to set-up a default value as well (see other variables at the beginning of the script)

**Comment by hannesm** [comment]
ah, ok. thx. done.

**Comment by samoht** [comment]
Thanks

**Pull request merged**
