### PR TITLE
Run tests before optional dependencies in case depopts are dirty after uninstall

### PR DESCRIPTION
**Pull request by dsheets**
Inspired by <https://travis-ci.org/mirage/ocaml-cohttp/jobs/58307674#L1819> and the subsequent failure on <https://travis-ci.org/mirage/ocaml-cohttp/jobs/58307674#L2216>. I don't know if this is actually the issue as I can't seem to reproduce the Travis failure.

### CODE REVIEW

**Comment by samoht** [comment]
This PR seems to make Irmin PR compile in much more time than before. Maybe we can optimise the testing strategy a bit more.

**Comment by dsheets** [comment]
Why do you think that is? Do the tests take a long time and depopts usually fail? Is there some unknown other interaction between tests and depopts?

**Comment by samoht** [comment]
The tests usually needs to install all the depots. But yea, the interaction is unclear.

**Comment by dsheets** [comment]
So the depopt removal is/was intentionally incomplete? We should try to batch the compile stages. It would be nice to have this written in a good PL.

**Comment by samoht** [comment]
> So the depopt removal is/was intentionally incomplete

Not sure if it was intentional, but it produces faster builds. To be clear, I'm fine with your fix, I'm just pointing out the possible drawbacks.

>  It would be nice to have this written in a good PL.

I completely agree with that ... @djs55 already (almost) volunteered o rewrite everything in OCaml in #33 :p

**Comment by dsheets** [comment]
I'm doing the rewrite now.

**Comment by djs55** [comment]
I'm sure dsheets will do a much better job than I would...

On Fri, Apr 17, 2015 at 6:48 PM, David Sheets <notifications@github.com>
wrote:

> I'm doing the rewrite now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/ocaml-travisci-skeleton/pull/37#issuecomment-94037989>
> .
>



-- 
Dave Scott

**Pull request merged**
