### PR TITLE
check for opam directory when linting

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by seliopou** [comment]
It's what `oasis2opam --local` generates.

**Comment by seliopou** [comment]
In addition `opam pin add .` will find the opam file if it's in `./opam` or `./opam/opam`.

**Comment by dsheets** [comment]
Should `opam lint`'s behavior be different to accomodate this without the conditional? I think the `opam` directory is supposed to be a supported metadata management style.

**Comment by hannesm** [comment]
@seliopou interesting.. does the opam directory contain anything apart from an opam file?  I actually like the common structure to have an opam at toplevel (or multiple in case a repository provides multiple opam packages).

**Comment by seliopou** [comment]
Here's an example from the [ocaml-aws](https://github.com/inhabitedtype/ocaml-aws/tree/master/opam) library. It contains an `opam`, `descr`, and `findlib` file, which makes it a bit easier to automate opam releases.

**Comment by seliopou** [comment]
@dsheets it probably should. But until it does, patching its behavior in the yorick script seems like a reasonable step forward.

**Comment by dsheets** [comment]
The CI fails because the `-fno-defer-pop` patch never made it to OCaml 3.12 on OS X? How did this work in the past??

**Comment by dsheets** [comment]
@seliopou I've reported the `opam lint` issue as ocaml/opam#2437.

**Comment by avsm** [comment]
I'm inclined to remove 3.12.1 support from these test scripts...

**Comment by dsheets** [comment]
#82 tracks 3.12 support.

**Pull request merged**
